# name: Create/update tag
# on: workflow_dispatch
# jobs:
#   create-tag:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 10
#       - uses: rickstaa/action-create-tag@v1
#         with:
#           tag: "latest"
#           message: "Latest release"
#           force_push_tag: "true"
name: Create/update tag
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  jobs:
    printInputs:
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}" 